### PR TITLE
New module to use neotrellis board with trellisM4

### PR DESCRIPTION
**Pull request by arofarn**
I've made a module to be able to extend the Trellism4 board with neotrellis (seesaw).
It consider the TrellisM4 as 2 "fake" neotrellis which can be use to create a multitrellis instance.

There is also an example code base on multitrellis example.

For soldering boards together : 
https://forums.adafruit.com/viewtopic.php?f=59&t=146778#p725825

### CODE REVIEW

**Comment by ladyada** [comment]
nice, i think that would be a new library though? you can subclass anything easily, that maybe makes more sense than having it in this library?

**Comment by arofarn** [comment]
OK, I'll try to create a new library.
Is your guide (https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/) still up to date ?

**Comment by ladyada** [comment]
yes!

**Comment by arofarn** [comment]
I should be OK there. The new library (my first, feedbacks welcome !) :
https://github.com/arofarn/NeoTrellisM4

I guess I can close this PR now.

Thanks you (and all the adafruit team) for the guides and cookiecutter template. It helps a lot !

**Comment by ladyada** [comment]
Thank Arofarn - You may want to name it something like `Arnofarn_CircuitPython_NeoTrellisM4` to match our library naming scheme, and then you can add it to our community bundle!
@kattni can help you with that :)

**Pull request closed without merging**
